name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: flamingelk
        password: ${{ secrets.HUB_LOGIN }}
    - name: Setup Node 12
      uses: actions/setup-node@v3
      with:
        node-version: '12'
    - name: Checkout, build and push
      uses: actions/checkout@v2
    - run: |
        IMAGE_NAME="universityofwarwick/sso-stub:latest"
        ./buildDocker.sh
        docker image tag sso-stub:latest ${IMAGE_NAME}
        docker push $IMAGE_NAME
